
import java.util.Timer;
import java.util.TimerTask;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alexandre
 */
public class SmartTermo extends javax.swing.JFrame {
    
    private float temperature;
    private int humidity;
    

    /**
     * Creates new form SmartTermo
     */
    public SmartTermo() {
        initComponents();
        simulateCTemp();
        temperature = 25;
        humidity = 60;
        jLabelCTemp.setText(temperature + "º");
        jLabelCH.setText(humidity + "%");
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonAumentarTemp = new javax.swing.JButton();
        jButtonDiminuirTemp = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonAumentH = new javax.swing.JButton();
        jButtonDiminuiH = new javax.swing.JButton();
        jLabelCTemp = new javax.swing.JLabel();
        jLabelDTemp = new javax.swing.JLabel();
        jLabelCH = new javax.swing.JLabel();
        jLabelDH = new javax.swing.JLabel();
        jButtonCº = new javax.swing.JButton();
        jButtonFº = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaLog = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Current Temp:");

        jLabel2.setText("Desired Temp:");

        jButtonAumentarTemp.setText("+");
        jButtonAumentarTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAumentarTempActionPerformed(evt);
            }
        });

        jButtonDiminuirTemp.setText("-");
        jButtonDiminuirTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDiminuirTempActionPerformed(evt);
            }
        });

        jLabel3.setText("Current H:");

        jLabel4.setText("Desired H:");

        jButtonAumentH.setText("+");
        jButtonAumentH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAumentHActionPerformed(evt);
            }
        });

        jButtonDiminuiH.setText("-");
        jButtonDiminuiH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDiminuiHActionPerformed(evt);
            }
        });

        jLabelCTemp.setText("25º");

        jLabelDTemp.setText("27º");

        jLabelCH.setText("60%");

        jLabelDH.setText("50%");

        jButtonCº.setText("Cº");
        jButtonCº.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCºActionPerformed(evt);
            }
        });

        jButtonFº.setText("Fº");
        jButtonFº.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFºActionPerformed(evt);
            }
        });

        jLabel5.setText("Date:");

        jLabel6.setText("jLabel6");

        jTextAreaLog.setColumns(20);
        jTextAreaLog.setRows(5);
        jScrollPane1.setViewportView(jTextAreaLog);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(jButtonDiminuiH))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(31, 31, 31)
                                .addComponent(jLabelCTemp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButtonAumentH)
                                        .addComponent(jLabel4)))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCH)
                                    .addComponent(jLabelDH)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jButtonAumentarTemp)
                                    .addComponent(jButtonCº))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(jLabelDTemp))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonDiminuirTemp)
                                            .addComponent(jButtonFº))))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabelCTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCH))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabelDTemp)
                    .addComponent(jLabelDH))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAumentarTemp)
                    .addComponent(jButtonDiminuirTemp)
                    .addComponent(jButtonAumentH)
                    .addComponent(jButtonDiminuiH))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCº)
                    .addComponent(jButtonFº))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAumentarTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAumentarTempActionPerformed
        temperature+=0.5;
        jLabelDTemp.setText(temperature + "º");
        jTextAreaLog.append("Aumentar a temperatura 0.5 graus");
    }//GEN-LAST:event_jButtonAumentarTempActionPerformed

    private void jButtonDiminuirTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDiminuirTempActionPerformed
        temperature-=0.5;
        jLabelDTemp.setText(temperature + "º");
        jTextAreaLog.append("Diminuir a temperatura 0.5 graus");
    }//GEN-LAST:event_jButtonDiminuirTempActionPerformed

    private void jButtonAumentHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAumentHActionPerformed
        humidity+=5;
        jLabelDH.setText(humidity + "º");
    }//GEN-LAST:event_jButtonAumentHActionPerformed

    private void jButtonDiminuiHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDiminuiHActionPerformed
        humidity-=5;
        jLabelDH.setText(humidity + "º");
    }//GEN-LAST:event_jButtonDiminuiHActionPerformed

    private void jButtonCºActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCºActionPerformed
       jLabelCTemp.setText(temperature + "ºC");
       jLabelDTemp.setText(temperature + "ºC");
    }//GEN-LAST:event_jButtonCºActionPerformed

    private void jButtonFºActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFºActionPerformed
       float fahrenheit = ((9*temperature)/5+32);
       jLabelCTemp.setText(fahrenheit + "ºF");
       jLabelDTemp.setText(fahrenheit + "ºF");
    }//GEN-LAST:event_jButtonFºActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SmartTermo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SmartTermo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SmartTermo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SmartTermo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SmartTermo().setVisible(true);
            }
        });
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAumentH;
    private javax.swing.JButton jButtonAumentarTemp;
    private javax.swing.JButton jButtonCº;
    private javax.swing.JButton jButtonDiminuiH;
    private javax.swing.JButton jButtonDiminuirTemp;
    private javax.swing.JButton jButtonFº;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelCH;
    private javax.swing.JLabel jLabelCTemp;
    private javax.swing.JLabel jLabelDH;
    private javax.swing.JLabel jLabelDTemp;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaLog;
    // End of variables declaration//GEN-END:variables

    public void simulateCTemp(){
        Timer timer = new Timer();
        
        TimerTask timerTask = new TimerTask() {

            @Override
            public void run() {
                temperature = (float) (Math.random()* 30);
                jLabelCTemp.setText(temperature + "º");
            }
        };
        timer.scheduleAtFixedRate(timerTask,0, 1000);
    }
}
